version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: laravel-apache-app
    container_name: laravel-apache-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
